# Playtron OS Taskfile
# https://taskfile.dev

version: "3"

env:
  IMAGE: playtronos
  PUBLIC_IMAGE: playtron-os

tasks:
  rpm-repo:
    desc: Build a local rpm-ostree repository with local RPMs.
    dir: rpm-ostree
    cmds:
      - mkdir -p /tmp/repo || true
      - echo "Checking if any RPMs exist in the /tmp/repo/ directory..."
      - ls /tmp/repo | grep rpm || exit 1
      - createrepo /tmp/repo
      - grep "  - local" playtron-os.yaml || sed -i s'/repos:/repos:\n  - local'/g playtron-os.yaml
      - echo -e "[local]\nname=local\nbaseurl=file:///tmp/repo\nenabled=1\nrepo_gpgcheck=0\ngpgcheck=0" > local.repo


  container-image:auth:
    desc: Authenticate with the container registry.
    preconditions:
      - sh: test -n "$REGISTRY"
        msg: "A value for REGISTRY must be provided"
      - sh: test -n "$REGISTRY_TOKEN"
        msg: "A value for REGISTRY_TOKEN must be provided"
    cmds:
      - mkdir -p ${XDG_RUNTIME_DIR}/containers
      - echo "{ \"auths\":{ \"${REGISTRY}\":{ \"auth\":\"${REGISTRY_TOKEN}\" } } }" > "${XDG_RUNTIME_DIR}/containers/auth.json"

  container-image:build:unstable:
    desc: Build the OCI container image using the latest upstream.
    preconditions:
      - sh: test -n "$TAG"
        msg: "A value for TAG must be provided"
    cmds:
      - mkdir -p rootfs/usr/lib
      - cat os-release.template | envsubst '${TAG}' > rootfs/usr/lib/os-release-playtron
      - podman build --no-cache --tag ${IMAGE}:${TAG} --file containerfiles/unstable .

  container-image:build:stable:
    desc: Build the OCI container image using a previously built image.
    preconditions:
      - sh: test -n "$TAG"
        msg: "A value for TAG must be provided"
    cmds:
      - mkdir -p rootfs/usr/lib
      - cat os-release.template | envsubst '${TAG}' > rootfs/usr/lib/os-release-playtron
      - podman build --no-cache --tag ${IMAGE}:${TAG} --file containerfiles/stable .

  container-image:push:
    desc: Push the OCI container image to the container registry.
    preconditions:
      - sh: test -n "$REGISTRY"
        msg: "A value for REGISTRY must be provided"
      - sh: grep "${REGISTRY}" "${XDG_RUNTIME_DIR}/containers/auth.json"
        msg: "Please use `container-image:auth` to authenticate with the registry"
      - sh: test -n "$TAG"
        msg: "A value for TAG must be provided"
      - sh: test -n "$PROJECT"
        msg: "A value for PROJECT must be provided"
    cmds:
      - podman push ${IMAGE}:${TAG} ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG}

  container-image:release:
    desc: Release the OCI container image by tagging it as `latest` in the container registry.
    preconditions:
      - sh: test -n "$REGISTRY"
        msg: "A value for REGISTRY must be provided"
      - sh: grep "${REGISTRY}" "${XDG_RUNTIME_DIR}/containers/auth.json"
        msg: "Please use `container-image:auth` to authenticate with the registry"
      - sh: test -n "$TAG"
        msg: "A value for TAG must be provided"
      - sh: test -n "$PROJECT"
        msg: "A value for PROJECT must be provided"
    cmds:
      - podman pull ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG}
      - podman push ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG} ${REGISTRY}/${PROJECT}/${IMAGE}:latest

  container-image:inspect:
    desc: Inspect the OCI container image by opening a shell inside the container.
    preconditions:
      - sh: test -n "$TAG"
        msg: "A value for TAG must be provided"
      - sh: test -n "$REGISTRY"
        msg: "A value for REGISTRY must be provided"
      - sh: test -n "$PROJECT"
        msg: "A value for PROJECT must be provided"
    cmds:
      - podman run --rm -it ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG} bash

  disk-image:kickstart:
    desc: Build the OS image from a container hosted in a registry using kickstart.
    dir: kickstart
    preconditions:
      - sh: test "$EUID" == 0
        msg: "This task must be run as root"
      - sh: test -n "$REGISTRY"
        msg: "A value for REGISTRY must be provided"
      - sh: test -n "$PROJECT"
        msg: "A value for PROJECT must be provided"
      - sh: test -n "$IMAGE"
        msg: "A value for IMAGE must be provided"
    cmds:
      - cat playtron-os_kickstart.cfg.template | envsubst '${REGISTRY} ${REGISTRY_TOKEN} ${PROJECT} ${IMAGE} ${TAG}' > playtron-os_kickstart.cfg
      - sudo setenforce 0
      - ./virt-install.sh
      - mv /var/lib/libvirt/images/playtron-os.img "/var/lib/libvirt/images/playtron-os.img_$(date -Iseconds)"
      - virsh undefine --nvram playtron-os


  disk-image:bootc:
    desc: Build the OS image from a container hosted in a registry using bootc image builder.
    preconditions:
      - sh: test "$EUID" == 0
        msg: "This task must be run as root"
      - sh: test -n "$REGISTRY"
        msg: "A value for REGISTRY must be provided"
      - sh: test -n "$PROJECT"
        msg: "A value for PROJECT must be provided"
      - sh: test -n "$IMAGE"
        msg: "A value for IMAGE must be provided"
    cmds:
      - rm -rf output
      - mkdir output
      - podman pull ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG}
      - podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v ./config.toml:/config.toml:ro -v ./output:/output -v /var/lib/containers/storage:/var/lib/containers/storage ghcr.io/playtron-os/bootc-image-builder:latest --type raw --rootfs btrfs ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG}

  disk-image:bootc:local:
    desc: Build the OS image from a local container using bootc image builder.
    preconditions:
      - sh: test "$EUID" == 0
        msg: "This task must be run as root"
      - sh: test -n "$IMAGE"
        msg: "A value for IMAGE must be provided"
    cmds:
      - rm -rf output
      - mkdir output
      - podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v ./config.toml:/config.toml:ro -v ./output:/output -v /var/lib/containers/storage:/var/lib/containers/storage ghcr.io/playtron-os/bootc-image-builder:latest --type raw --rootfs btrfs localhost/${IMAGE}:${TAG}

  repo:update:
    desc: "Update the package repository"
    cmds:
      - rm -rf /tmp/repo
      - mkdir -p /tmp/repo
      - aws s3 cp s3://playtron-dev2-global-os-public/repos/playtron-app/x86_64/ /tmp/repo/ --recursive
      - read -p "Copy new packages into /tmp/repo and press ENTER to continue"
      - createrepo /tmp/repo
      - aws s3 sync /tmp/repo/ s3://playtron-dev2-global-os-public/repos/playtron-app/x86_64/

  public:auth:
    desc: Authenticate with the GitHub container registry.
    preconditions:
      - sh: test -n "$GITHUB_USER"
        msg: "A value for GITHUB_USER must be provided"
      - sh: test -n "$GITHUB_TOKEN"
        msg: "A value for GITHUB_TOKEN must be provided"
    cmds:
      - echo $GITHUB_TOKEN | podman login ghcr.io -u $GITHUB_USER --password-stdin

  public:push:
    desc: Publish the container to the public registry.
    preconditions:
      - sh: test -n "$REGISTRY"
        msg: "A value for REGISTRY must be provided"
      - sh: grep "${REGISTRY}" "${XDG_RUNTIME_DIR}/containers/auth.json"
        msg: "Please use `container-image:auth` to authenticate with the registry"
      - sh: grep "ghcr.io" "${XDG_RUNTIME_DIR}/containers/auth.json"
        msg: "Please use `public:auth` to authenticate with the GitHub registry"
      - sh: test -n "$PROJECT"
        msg: "A value for PROJECT must be provided"
      - sh: test -n "$TAG"
        msg: "A value for TAG must be provided"
    cmds:
      - podman pull ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG}
      - podman push ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG} ghcr.io/playtron-os/${PUBLIC_IMAGE}:${TAG}

  public:release:
    desc: Publish the container to the public registry with the tag 'latest'.
    preconditions:
      - sh: test -n "$REGISTRY"
        msg: "A value for REGISTRY must be provided"
      - sh: grep "${REGISTRY}" "${XDG_RUNTIME_DIR}/containers/auth.json"
        msg: "Please use `container-image:auth` to authenticate with the registry"
      - sh: grep "ghcr.io" "${XDG_RUNTIME_DIR}/containers/auth.json"
        msg: "Please use `public:auth` to authenticate with the GitHub registry"
      - sh: test -n "$PROJECT"
        msg: "A value for PROJECT must be provided"
      - sh: test -n "$TAG"
        msg: "A value for TAG must be provided"
    cmds:
      - podman pull ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG}
      - podman push ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG} ghcr.io/playtron-os/${PUBLIC_IMAGE}:${TAG}
      - podman push ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG} ghcr.io/playtron-os/${PUBLIC_IMAGE}:latest

  package-list:
    desc: Generate a list of packages that are installed in a remote container without version numbers
    preconditions:
      - sh: test -n "$REGISTRY"
        msg: "A value for REGISTRY must be provided"
      - sh: grep "${REGISTRY}" "${XDG_RUNTIME_DIR}/containers/auth.json"
        msg: "Please use `container-image:auth` to authenticate with the registry"
      - sh: grep "${REGISTRY}" "${XDG_RUNTIME_DIR}/containers/auth.json"
        msg: "Please use `container-image:auth` to authenticate with the registry"
      - sh: test -n "$PROJECT"
        msg: "A value for PROJECT must be provided"
      - sh: test -n "$TAG"
        msg: "A value for TAG must be provided"
    cmds:
      - podman pull ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG}
      - podman run -it ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG} rpm -qa --qf "%{NAME}\n" | sort -u > playtron-os-${TAG}.pkg-list.txt

  package-list:versioned:
    desc: Generate a list of packages that are installed in a remote container with version numbers
    preconditions:
      - sh: test -n "$REGISTRY"
        msg: "A value for REGISTRY must be provided"
      - sh: grep "${REGISTRY}" "${XDG_RUNTIME_DIR}/containers/auth.json"
        msg: "Please use `container-image:auth` to authenticate with the registry"
      - sh: grep "${REGISTRY}" "${XDG_RUNTIME_DIR}/containers/auth.json"
        msg: "Please use `container-image:auth` to authenticate with the registry"
      - sh: test -n "$PROJECT"
        msg: "A value for PROJECT must be provided"
      - sh: test -n "$TAG"
        msg: "A value for TAG must be provided"
    cmds:
      - podman pull ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG}
      - podman run -it ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG} rpm -qa | sort -u > playtron-os-${TAG}.pkg-list.versioned.txt

  package-list:local:versioned:
    desc: Generate a list of packages that are installed in a local container with version numbers
    preconditions:
      - sh: test -n "$PROJECT"
        msg: "A value for PROJECT must be provided"
      - sh: test -n "$TAG"
        msg: "A value for TAG must be provided"
    cmds:
      - podman run -it ${IMAGE}:${TAG} rpm -qa | sort -u > playtron-os-${TAG}.pkg-list.versioned.txt
