FROM playtron-os-base:local
# Docker/Podman will automatically populate this with the host architecture.
# "linux/amd64" for x86. "linux/arm64" for Arm.
ARG TARGETPLATFORM

# Copy over repository files.
RUN rm -f /etc/yum.repos.d/*
## Fedora.
COPY fedora-40.repo fedora-40-updates.repo fedora-updates-archive.repo /etc/yum.repos.d/
## kernel-fsync.
COPY kernel-fsync.repo /etc/yum.repos.d/
## RPM Fusion.
COPY rpmfusion-free.repo rpmfusion-free-updates.repo rpmfusion-free-updates-testing.repo rpmfusion-nonfree.repo rpmfusion-nonfree-tainted.repo rpmfusion-nonfree-updates.repo rpmfusion-nonfree-updates-testing.repo /etc/yum.repos.d/
## Playtron.
COPY playtron-app-x86_64.repo playtron-gaming-i386.repo playtron-gaming-x86_64.repo /etc/yum.repos.d/


# On x86, also install 32-bit Mesa.
# Our Arm builds are only 64-bit.
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
  rpm-ostree install \
  mesa-dri-drivers.i686 \
  mesa-filesystem.i686 \
  mesa-libd3d.i686 \
  mesa-libEGL.i686 \
  mesa-libgbm.i686 \
  mesa-libGL.i686 \
  mesa-libglapi.i686 \
  mesa-libOpenCL.i686 \
  mesa-libOSMesa.i686 \
  mesa-libxatracker.i686 \
  mesa-va-drivers.i686 \
  mesa-vdpau-drivers.i686 \
  mesa-vulkan-drivers.i686; fi \
  && ostree container commit

RUN rpm-ostree install \
  steam.i686 \
  && ostree container commit

# Create the "playtron" user manually.
# https://bugzilla.redhat.com/show_bug.cgi?id=1838859
# Put the user in the "wheel" group for elevated privileges and "input" for Autotest to work.
RUN grep -E '^input:' /usr/lib/group | tee -a /etc/group && \
  useradd -G wheel,input playtron && \
  echo "playtron:playtron" | chpasswd && \
  chown -R -v 1000:1000 /var/home/playtron

# Hide the GRUB boot menu.
RUN crudini --ini-options=nospace --set /etc/default/grub "" GRUB_TIMEOUT 0 && \
  crudini --ini-options=nospace --set /etc/default/grub "" GRUB_TIMEOUT_STYLE hidden && \
  ostree container commit

# Copy/override files
COPY rootfs/etc/hostname /etc/
COPY rootfs/etc/bluetooth/main.conf /etc/bluetooth/
COPY rootfs/usr/lib/os-release-playtron /usr/lib/
COPY rootfs/usr/share/plymouth/themes/spinner/watermark.png /usr/share/plymouth/themes/spinner/

# Finalize initramfs
RUN KERNEL=$(echo /lib/modules/*/initramfs.img | cut -d'/' -f4) \
  && dracut --reproducible -v --add 'ostree' -f --no-hostonly --kver ${KERNEL} /lib/modules/${KERNEL}/initramfs.img \
  && ostree container commit
