FROM playtron-os-base:latest
# Docker/Podman will automatically populate this with the host architecture.
# "linux/amd64" for x86. "linux/arm64" for Arm.
ARG TARGETPLATFORM

# Copy over repository files.
## Fedora.
## As of 2024-06-14, this repository was removed from the quay.io/fedora/fedora-bootc:40 image.
COPY fedora-updates-archive.repo /etc/yum.repos.d/
## kernel-fsync.
COPY kernel-fsync.repo /etc/yum.repos.d/
## RPM Fusion.
COPY rpmfusion-free.repo rpmfusion-free-updates.repo rpmfusion-free-updates-testing.repo rpmfusion-nonfree.repo rpmfusion-nonfree-tainted.repo rpmfusion-nonfree-updates.repo rpmfusion-nonfree-updates-testing.repo /etc/yum.repos.d/
## Playtron.
COPY playtron-app-x86_64.repo playtron-gaming-i386.repo playtron-gaming-x86_64.repo /etc/yum.repos.d/

# Install DNF 5 first.
RUN rpm-ostree install \
  dnf5 \
  dnf5-plugins \
  && ostree container commit

ENV CMD_INSTALL="dnf5 install -y --setopt=install_weak_deps=false --setopt=max_parallel_downloads=10"

# On x86, also install 32-bit Mesa.
# Our Arm builds are only 64-bit.
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
  ${CMD_INSTALL} \
  mesa-dri-drivers.i686 \
  mesa-filesystem.i686 \
  mesa-libd3d.i686 \
  mesa-libEGL.i686 \
  mesa-libgbm.i686 \
  mesa-libGL.i686 \
  mesa-libglapi.i686 \
  mesa-libOpenCL.i686 \
  mesa-libOSMesa.i686 \
  mesa-libxatracker.i686 \
  mesa-va-drivers.i686 \
  mesa-vdpau-drivers.i686 \
  mesa-vulkan-drivers.i686; fi \
  && ostree container commit

RUN ${CMD_INSTALL} \
  steam.i686 \
  && ostree container commit


# Add firmware and configuration files needed for Steam Deck OLED audio support.
RUN wget https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/steamdeck-dsp-0.49-1-any.pkg.tar.zst -O /tmp/steamdeck-dsp.tar.zst \
  # There are tar extraction errors about file system attributes that can be safely ignored.
  && tar -xvf /tmp/steamdeck-dsp.tar.zst -C / || true \
  # Verify that the extraction actually worked.
  && ls /usr/lib/firmware/amd/sof/sof-vangogh-code.bin \
  && rm -f /tmp/steamdeck-dsp.tar.zst \
  && ostree container commit

# Copy/override files
COPY rootfs/etc/bluetooth/main.conf /etc/bluetooth/
COPY rootfs/usr/lib/os-release-playtron /usr/lib/
COPY rootfs/usr/share/plymouth/themes/spinner/watermark.png /usr/share/plymouth/themes/spinner/
